/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// eye_detection
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78000/CNN --prefix eye_detection --checkpoint-file trained/ai85-eye-qat-q.pth.tar --config-file networks/eye-hwc.yaml --fifo --softmax --device MAX78000 --timer 0 --display-checkpoint --verbose

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "mxc.h"
#include "mxc_device.h"
#include "mxc_delay.h"
#include "fcr_regs.h"
#include "icc.h"
#include "led.h"
#include "pb.h"
#include "dma.h"
#include "tmr.h"
#include "uart.h"
#include "board.h"
#include "camera.h"
#include "cnn.h"
#include "weights.h"
#include "sampledata.h"
#include "sampleoutput.h"
#include "utils.h"

#define DEBUG_COMPORT MXC_UART0

#define IMAGE_SIZE_X (128)
#define IMAGE_SIZE_Y (128)
#define CON_BAUD 115200 * 1

#define X_START 0
#define Y_START 0

#define CAMERA_FREQ (5 * 1000 * 1000)

const char classes[CNN_NUM_OUTPUTS][10] = { "Closed", "Open" };

// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t ml_softmax[CNN_NUM_OUTPUTS];

volatile uint32_t cnn_time; // Stopwatch

static uint32_t input_0[IMAGE_SIZE_X * IMAGE_SIZE_Y];

static uint8_t image_buffer[IMAGE_SIZE_X * IMAGE_SIZE_Y * 3];

static uint32_t lens;
static uint32_t ws;
static uint32_t hs;

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  int i;
  const uint32_t *in0 = input_0;

  for (i = 0; i < 16384; i++) {
    // Remove the following line if there is no risk that the source would overrun the FIFO:
    while (((*((volatile uint32_t *) 0x50000004) & 1)) != 0); // Wait for FIFO 0
    *((volatile uint32_t *) 0x50000008) = *in0++; // Write FIFO 0
  }
}

void capture_process_camera(void)
{
  uint8_t *raw;
  uint32_t imgLen;
  uint32_t w, h;

  int cnt = 0;

  uint8_t r, g, b;
  //uint16_t rgb;
  //int j = 0;
  
  uint8_t *data = NULL;
  stream_stat_t *stat;
  
  camera_start_capture_image();

  // Get the details of the image from the camera driver.
  camera_get_image(&raw, &imgLen, &w, &h);

  printf("W:%d H:%d L:%d \n", w, h, imgLen);

  lens = imgLen;
  ws = w;
  hs = h;

  for (int row = 0; row < h; row++) {
    // Wait until camera streaming buffer is full
    while ((data = get_camera_stream_buffer()) == NULL) {
      if (camera_is_image_rcv()) {
        break;
      }
    }

    for (int k = 0; k < 4 * w; k += 4) {
      // data format: 0x00bbggrr
      r = data[k];
      g = data[k + 1];
      b = data[k + 2];
      //skip k+3

      uint8_t l = 0.299 * r + 0.587 * g + 0.114 * b;

      // change the range from [0,255] to [-128,127] and store in buffer for CNN
      input_0[cnt++] = ((l << 16) | (l << 8) | l) ^ 0x00808080;
      //input_0[cnt++] = ((b << 16) | (g << 8) | r) ^ 0x00808080;
    }

    release_camera_stream_buffer();
  }

  //camera_sleep(1);
  
  stat = get_camera_stream_statistic();

  if (stat->overflow_count > 0) {
    printf("OVERFLOW DISP = %d\n", stat->overflow_count);
    LED_On(LED2); // Turn on red LED if overflow detected
    while (1) {}
  }
  
}

int main(void)
{
  int i;
  int digs, tens;
  int ret = 0;
  int dma_channel;
  int slaveAddress;
  int id;

  // Wait for PMIC 1.8V to become available, about 180ms after power up.
  MXC_Delay(200000);
  /* Enable camera power */
  Camera_Power(POWER_ON);

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  /* Configure P2.5, turn on the CNN Boost */
  cnn_boost_enable(MXC_GPIO2, MXC_GPIO_PIN_5);

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine

  // Initialize DMA for camera interface
  MXC_DMA_Init();
  dma_channel = MXC_DMA_AcquireChannel();

  mxc_uart_regs_t *ConsoleUart = MXC_UART_GET_UART(CONSOLE_UART);

  if ((ret = MXC_UART_Init(ConsoleUart, CON_BAUD, MXC_UART_IBRO_CLK)) != E_NO_ERROR) {
    return ret;
  }

  // Initialize camera.
  printf("Init Camera.\n");
  camera_init(CAMERA_FREQ);

  slaveAddress = camera_get_slave_address();
  printf("Camera I2C slave address: %02x\n", slaveAddress);

  // Obtain product ID of the camera.
  ret = camera_get_product_id(&id);

  if (ret != STATUS_OK) {
    printf("Error returned from reading camera id. Error %d\n", ret);
    return -1;
  }

  printf("Camera ID detected: %04x\n", id);

  ret = camera_setup(IMAGE_SIZE_X, IMAGE_SIZE_Y, PIXFORMAT_RGB888, FIFO_THREE_BYTE, STREAMING_DMA, dma_channel);

  if (ret != STATUS_OK) {
    printf("Error returned from setting up camera. Error %d\n", ret);
    return -1;
  }

  MXC_Delay(SEC(1));

  camera_write_reg(0x11, 0x0);

  printf("********** Press PB1(SW1) to capture an image **********\r\n");
  while (!PB_Get(0)) {}

  /* Enable CNN clock */
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN);

  camera_start_capture_image();

  while(1) {
    LED_Off(LED1);
    LED_Off(LED2);

    capture_process_camera(); // Capture image from camera

    cnn_start(); // Start CNN processing
    load_input(); // Load data input via FIFO

    while (cnn_time == 0)
      MXC_LP_EnterSleepMode(); // Wait for CNN

    // Unload CNN data
    cnn_unload((uint32_t *) ml_data);
    cnn_stop(); // Stop CNN clock

    // Softmax
    softmax_q17p14_q15((const q31_t *) ml_data, CNN_NUM_OUTPUTS, ml_softmax);

    printf("Approximate data loading and inference time: %u us\n\n", cnn_time);

    printf("Classification results:\n");
    for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
      digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
      tens = digs % 10;
      digs = digs / 10;
      printf("[%7d] -> Class %d %8s: %d.%d%%\r\n", ml_data[i], i, classes[i], digs, tens);
    }

    int count = 0;
    for(int i=0; i < lens/4; i++){
      image_buffer[count++] = (uint8_t)((input_0[i] >> 16) & 0xFF);
      image_buffer[count++] = (uint8_t)((input_0[i] >> 8) & 0xFF);
      image_buffer[count++] = (uint8_t)(input_0[i] & 0xFF);
    }

    printf("\n");

    printf("********** Press PB1(SW1) to capture an image **********\r\n");
    printf("********** Press PB2(SW2) to send image to PC **********\r\n");
    while (!PB_Get(0) && !PB_Get(1)) {}

    if(PB_Get(1)) {
      utils_send_img_to_pc(image_buffer, lens/4*3, ws, hs, (uint8_t *)"RGB888");
    }

    while(!PB_Get(0)) {}

    camera_start_capture_image();
    
  }
  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 51,368,960 ops (50,432,000 macc; 936,960 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 7,340,032 ops (7,077,888 macc; 262,144 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 19,267,584 ops (18,874,368 macc; 393,216 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 19,070,976 ops (18,874,368 macc; 196,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 4,792,320 ops (4,718,592 macc; 73,728 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 600,064 ops (589,824 macc; 10,240 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 295,936 ops (294,912 macc; 1,024 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 2,048 ops (2,048 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 57,776 bytes out of 442,368 bytes total (13.1%)
  Bias memory:   2 bytes out of 2,048 bytes total (0.1%)
*/

