/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// eye_detection
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78000/CNN --prefix eye_detection --checkpoint-file trained/ai85-eye-qat-q.pth.tar --config-file networks/eye-hwc.yaml --fifo --softmax --device MAX78000 --timer 0 --display-checkpoint --verbose

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>

#include "mxc.h"
#include "mxc_device.h"
#include "mxc_delay.h"
#include "fcr_regs.h"
#include "icc.h"
#include "led.h"
#include "pb.h"
#include "dma.h"
#include "tmr.h"
#include "uart.h"
#include "board.h"
#include "camera.h"
#include "cnn.h"
#include "weights.h"
#include "sampledata.h"
#include "sampleoutput.h"
#include "utils.h"
#include "risk_monitor.h"
#include "gpio.h"     // <-- for haptic GPIO
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "i2c.h"
#include "adxl345.h"
#include "mxc_device.h"
#include "mxc_delay.h"
#include "board.h"
#include "mxc_errors.h"
#include "g_force.h"



#define DEBUG_COMPORT MXC_UART0

#define IMAGE_SIZE_X (128)
#define IMAGE_SIZE_Y (128)
#define CON_BAUD 115200 * 1

#define X_START 0
#define Y_START 0

#define CAMERA_FREQ (5 * 1000 * 1000)

const char classes[CNN_NUM_OUTPUTS][10] = { "Closed", "Open" };


/***** Definitions *****/
#define I2C_MASTER MXC_I2C1 ///< I2C instance (Featherboard)

#define I2C_FREQ 400000 ///< I2C clock frequency
//#define SENSOR_HUB_ADDR 0x55 //MAX32664 Sensor Hub Starting Address 
#define ADXL345_ADDR 0x1D //ADXL345 Device Starting Address with SDO high
#define ARDUINO_ADDR   0x55

#define E_NO_ERROR 0 //Variable to check for errors over I2C initialization


#define SENSOR_I2C_PORT    MXC_I2C1

#define SUBCMD_EN 0x00 //enter application mode of sensor 
#define READ_DATA_CMD 0x12 //address for read data command 


//ADXL345 Commands


#define ADXL345_PWR_CTRL 0x2D //Set device in measurement mode  
#define ADXL345_DTA_FORM 0x31 //Manipulate format of data in terms of G's
#define ADXL345_BW_Rate 0x2C //manipulate sampling rate of accelerometer 
#define ADXL345_DTA 0x32 //Beginning address of readable data


// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t  ml_softmax[CNN_NUM_OUTPUTS];

volatile uint32_t cnn_time; // Stopwatch

static uint32_t input_0[IMAGE_SIZE_X * IMAGE_SIZE_Y];
static uint8_t  image_buffer[IMAGE_SIZE_X * IMAGE_SIZE_Y * 3];

static uint32_t lens;
static uint32_t ws;
static uint32_t hs;

static RiskMonitor g_risk_monitor;

// Make ConsoleUart available to helper functions
static mxc_uart_regs_t *ConsoleUart = NULL;

// -------------------- HAPTIC (DFR0440) SETUP --------------------

// Use same pin as your I2C demo: GPIO1.6 as haptic driver output.
static mxc_gpio_cfg_t g_hapDriver = {
    .port   = MXC_GPIO1,
    .mask   = MXC_GPIO_PIN_6,
    .func   = MXC_GPIO_FUNC_OUT,
    .pad    = MXC_GPIO_PAD_NONE,
    .vssel  = MXC_GPIO_VSSEL_VDDIOH,
    .drvstr = MXC_GPIO_DRVSTR_0,
};

static void Haptic_Init(void)
{
    if (MXC_GPIO_Config(&g_hapDriver) != E_NO_ERROR) {
        printf("Error configuring haptic GPIO\n");
        while (1) {}
    }
    // Start with haptic off
    MXC_GPIO_OutClr(g_hapDriver.port, g_hapDriver.mask);
}

static void Haptic_Set(bool on)
{
    if (on) {
        MXC_GPIO_OutSet(g_hapDriver.port, g_hapDriver.mask);
    } else {
        MXC_GPIO_OutClr(g_hapDriver.port, g_hapDriver.mask);
    }
}

// ---------------------------------------------------------------

void fail(void)
{
    printf("\n*** FAIL ***\n\n");
    while (1) {}
}

void load_input(void)
{
    // This function loads the sample data input -- replace with actual data
    int i;
    const uint32_t *in0 = input_0;

    for (i = 0; i < 16384; i++) {
        // Remove the following line if there is no risk that the source would overrun the FIFO:
        while (((*((volatile uint32_t *)0x50000004) & 1)) != 0) {
            /* Wait for FIFO 0 */
        }
        *((volatile uint32_t *)0x50000008) = *in0++; // Write FIFO 0
    }
}

void capture_process_camera(void)
{
    uint8_t *raw;
    uint32_t imgLen;
    uint32_t w, h;

    int cnt = 0;

    uint8_t r, g, b;
    uint8_t *data = NULL;
    stream_stat_t *stat;

    camera_start_capture_image();

    // Get the details of the image from the camera driver.
    camera_get_image(&raw, &imgLen, &w, &h);

    printf("W:%d H:%d L:%d \n", w, h, imgLen);

    lens = imgLen;
    ws   = w;
    hs   = h;

    for (int row = 0; row < (int)h; row++) {
        // Wait until camera streaming buffer is full
        while ((data = get_camera_stream_buffer()) == NULL) {
            if (camera_is_image_rcv()) {
                break;
            }
        }

        for (int k = 0; k < 4 * (int)w; k += 4) {
            // data format: 0x00bbggrr
            r = data[k];
            g = data[k + 1];
            b = data[k + 2];
            // skip k+3

            uint8_t l = (uint8_t)(0.299f * r + 0.587f * g + 0.114f * b);

            // change the range from [0,255] to [-128,127] and store in buffer for CNN
            input_0[cnt++] = ((l << 16) | (l << 8) | l) ^ 0x00808080;
        }

        release_camera_stream_buffer();
    }

    stat = get_camera_stream_statistic();

    if (stat->overflow_count > 0) {
        printf("OVERFLOW DISP = %d\n", stat->overflow_count);
        LED_On(LED2); // Turn on red LED if overflow detected
        while (1) {}
    }
}

// -------------------- Serial helper --------------------
// Non-blocking check for a backslash key '\' from the host console.
// Returns 1 if backslash was received (and consumes the byte), 0 otherwise.
static int check_for_backslash(void)
{
    int ch;

    if (ConsoleUart == NULL) {
        return 0;
    }

    // MXC_UART_ReadCharacterRaw returns character (>=0) or error (<0) when none.
    ch = MXC_UART_ReadCharacterRaw(ConsoleUart);
    if (ch >= 0) {
        if ((char)ch == '\\') {
            return 1;
        }
        // If you want to echo or handle other keys you can do that here.
    }
    return 0;
}
// ----------------------------------------------------

// -------------------- ADXL345 continuous polling support --------------------
// Make the ADXL device and the latest accel values global so we can poll from
// idle loops and keep values fresh even when waiting for keypresses.
static struct adxl345_dev *g_adxl_dev = NULL;
static float g_x_g = 0.0f, g_y_g = 0.0f, g_z_g = 0.0f;
static float g_gmag = 0.0f;
static float g_final_g_xz = 0.0f;

// Poll accelerometer once (non-blocking in sense of other code; the driver call may be blocking briefly)
static void PollAccel(void)
{
    if (g_adxl_dev == NULL) return;

    // read xyz from ADXL345 and update globals
    adxl345_get_g_xyz(g_adxl_dev, &g_x_g, &g_y_g, &g_z_g);
    g_gmag = gforce_mag_from_xyz(g_x_g, g_y_g, g_z_g);
    g_final_g_xz = gforce_weighted_from_xz(g_x_g, g_z_g);
}

// ----------------------------------------------------

int main(void)
{
    int i;
    int digs, tens;
    int ret = 0;
    int dma_channel;
    int slaveAddress;
    int id;

    // Wait for PMIC 1.8V to become available, about 180ms after power up.
    MXC_Delay(200000);

    /* Enable camera power */
    Camera_Power(POWER_ON);

    MXC_ICC_Enable(MXC_ICC0); // Enable cache

    // Switch to 100 MHz clock
    MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
    SystemCoreClockUpdate();

    // Enable peripheral, enable CNN interrupt, turn on CNN clock
    // CNN clock: APB (50 MHz) div 1
    cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK,
               MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

    /* Configure P2.5, turn on the CNN Boost */
    cnn_boost_enable(MXC_GPIO2, MXC_GPIO_PIN_5);

    cnn_init();          // Bring state machine into consistent state
    cnn_load_weights();  // Load kernels
    cnn_load_bias();
    cnn_configure();     // Configure state machine

    // Initialize fused risk monitor
    // Threshold set to 0.15 so score > 0.15 triggers, as requested.
    RiskMonitor_Init(&g_risk_monitor,
                     0.15f,  // threshold
                     0.6f,   // eye_weight
                     0.2f,   // hr_weight (minimal influence for now)
                     0.2f,   // accel_weight (minimal influence for now)
                     0.0f,
                     70.0f,
                     1.0f);

    // Initialize DMA for camera interface
    MXC_DMA_Init();
    dma_channel = MXC_DMA_AcquireChannel();

    // Make the console UART available globally
    ConsoleUart = MXC_UART_GET_UART(CONSOLE_UART);

    if ((ret = MXC_UART_Init(ConsoleUart, CON_BAUD, MXC_UART_IBRO_CLK)) != E_NO_ERROR) {
        return ret;
    }

    // Initialize camera.
    printf("Init Camera.\n");
    camera_init(CAMERA_FREQ);

    slaveAddress = camera_get_slave_address();
    printf("Camera I2C slave address: %02x\n", slaveAddress);

    // Obtain product ID of the camera.
    ret = camera_get_product_id(&id);

    if (ret != STATUS_OK) {
        printf("Error returned from reading camera id. Error %d\n", ret);
        return -1;
    }

    printf("Camera ID detected: %04x\n", id);

    ret = camera_setup(IMAGE_SIZE_X, IMAGE_SIZE_Y,
                       PIXFORMAT_RGB888, FIFO_THREE_BYTE,
                       STREAMING_DMA, dma_channel);

    if (ret != STATUS_OK) {
        printf("Error returned from setting up camera. Error %d\n", ret);
        return -1;
    }

    MXC_Delay(SEC(1));
    camera_write_reg(0x11, 0x0);

    // Init haptic GPIO (DFR0440)
    Haptic_Init();

    printf("********** Press '\\' on your PC console to start 2-second eye window **********\r\n");
    printf("Sampling at ~0.5 s per frame (%d frames per window).\r\n", EYE_WINDOW_SIZE);

    /* Enable CNN clock */
    MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN);

    // ______________________________________________________________________________________________
    // Move ADXL345 device handle to global so PollAccel can read it at any time
    struct adxl345_init_param init_param;
    int32_t status = 0;
    
    // Acceleration readings are now global (g_x_g, g_y_g, etc.)

    printf("\n***** MAX78000 ADXL345 I2C Demo (continuous polling) *****\n");

    // Initialize parameters for the ADXL345 driver
    init_param.i2c_inst = SENSOR_I2C_PORT;
    init_param.i2c_addr = ADXL345_ADDR;
    init_param.dev_type = ID_ADXL345;
    
    // Set preferred range and resolution (optional, defaults to +/- 2g, 10-bit)
    init_param.selected_range = ADXL345_RANGE_PM_8G; // Set to +/- 8g range
    init_param.full_resolution_set = ADXL345_FULL_RES; // Enable Full Resolution (13-bit)

    // 1. Initialize the ADXL345 device (initializes I2C and checks device ID)
    status = adxl345_init(&g_adxl_dev, init_param);
    
    if (status != 0) {
        printf("ERROR: ADXL345 Initialization Failed! (Status: %ld)\n", status);
        printf("Check I2C connections and slave address (0x%X).\n", ADXL345_ADDR);
        MXC_Delay(MXC_DELAY_SEC(5));
        return 1;
    }
    
    printf("ADXL345 initialized successfully.\n");
    
    // 2. Configure the sensor's measurement properties
    
    // Set range and resolution
    adxl345_set_range_resolution(g_adxl_dev, 
                                 init_param.selected_range, 
                                 init_param.full_resolution_set);
    
    // Put the device in Measure Mode (continuous polling)
    adxl345_set_power_mode(g_adxl_dev, 1);
    printf("ADXL345 set to Measure Mode.\n");

    // Immediately sample once to prime the globals
    //PollAccel();

    while (1) {
        // Wait for '\' key from PC to start a new 2-second window
        printf("\r\n[RiskMonitor] Waiting for '\\' to start 2-second eye window...\r\n");
        // Poll the accelerometer continuously while idle so values stay fresh
        while (!check_for_backslash()) {
            //PollAccel();
            // Small sleep so this loop doesn't busy-wait too hard
            MXC_Delay(MSEC(10));
        }

        printf("\r\n[RiskMonitor] Starting 2-second eye window...\r\n");

        // Collect EYE_WINDOW_SIZE frames over approximately 2 seconds
        for (int sample_idx = 0; sample_idx < EYE_WINDOW_SIZE; ++sample_idx) {
            LED_Off(LED1);
            LED_Off(LED2);

            // Capture image from camera into input_0[]
            capture_process_camera();

            // Run CNN on captured image
            cnn_time = 0;
            cnn_start();
            load_input();

            // Wait for CNN
            while (cnn_time == 0) {
                MXC_LP_EnterSleepMode();
            }

            // Unload CNN data and stop clock
            cnn_unload((uint32_t *)ml_data);
            cnn_stop();

            // Softmax
            softmax_q17p14_q15((const q31_t *)ml_data,
                               CNN_NUM_OUTPUTS, ml_softmax);

            // Eye-closed confidence for "Closed" class (index 0) as 0–100%
            float eye_closed_conf_pct = 0.0f;
            if (CNN_NUM_OUTPUTS >= 1) {
                eye_closed_conf_pct =
                    ((float)ml_softmax[0] * 100.0f) / 32768.0f;
                if (eye_closed_conf_pct < 0.0f)  eye_closed_conf_pct = 0.0f;
                if (eye_closed_conf_pct > 100.0f) eye_closed_conf_pct = 100.0f;
            }

            // --- read accelerometer now and compute weighted XZ value ---
            // Use the latest polled value so reading is effectively continuous.
            // But also poll now to get the freshest sample at inference time.
            //PollAccel(); // refresh before computing/federating into RiskMonitor
            //float eye_accel_xz = g_final_g_xz;

            // Update RiskMonitor with real accel (final_g_xz) instead of 0.0f
            bool alert = RiskMonitor_Update(&g_risk_monitor,
                                            eye_closed_conf_pct,
                                            0.0f, 0.7f);       // TODO: real HR ROC (BPM/s)
                                            //eye_accel_xz); // <-- pass weighted XZ g here

            float score = RiskMonitor_GetScore(&g_risk_monitor);

            // Print the sample, include accel XZ on the same line
            printf("Sample %d/%d: eye_closed_conf=%.1f%%, score=%.3f, accel_xz=%.3f g, alert=%d\r\n",
                   sample_idx + 1, EYE_WINDOW_SIZE,
                   eye_closed_conf_pct, score, 0.7f, alert ? 1 : 0);

            // Per-0.5s BUZZ / no buzz + haptic drive
            if (alert) {
                printf("BUZZ\r\n");
                Haptic_Set(true);
            } else {
                printf("no buzz\r\n");
                Haptic_Set(false);
            }

            // Re-pack last grayscale image into RGB888 buffer for PC download
            int count = 0;
            for (int pix = 0; pix < (int)(lens / 4); ++pix) {
                image_buffer[count++] =
                    (uint8_t)((input_0[pix] >> 16) & 0xFF);
                image_buffer[count++] =
                    (uint8_t)((input_0[pix] >> 8) & 0xFF);
                image_buffer[count++] =
                    (uint8_t)(input_0[pix] & 0xFF);
            }

            // Delay to roughly hit 0.5 s per frame, ignoring processing time
            if (sample_idx < (EYE_WINDOW_SIZE - 1)) {
                MXC_Delay(SEC(1) / 2); // ~0.5 s
            }
        } // end 2-second window loop

        float final_score = RiskMonitor_GetScore(&g_risk_monitor);
        bool  final_alert = RiskMonitor_GetAlertFlag(&g_risk_monitor);

        printf("\r\n[RiskMonitor] 2-second window complete.\r\n");
        printf("RiskMonitor: score=%.3f, alert=%d\r\n",
               final_score, final_alert ? 1 : 0);

        if (final_alert) {
            printf("BUZZ\r\n");
            Haptic_Set(true);
            MXC_Delay(SEC(2)); // Buzz for 1 second
            Haptic_Set(false);
        } else {
            printf("no buzz\r\n");
            Haptic_Set(false);
        }

        printf("Approximate data loading and inference time (last frame): %u us\r\n\n",
               cnn_time);

        printf("Classification results (last frame in window):\r\n");
        for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
            digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
            tens = digs % 10;
            digs = digs / 10;
            printf("[%7d] -> Class %d %8s: %d.%d%%\r\n",
                   ml_data[i], i, classes[i], digs, tens);
        }

        printf("\n");
        printf("********** Press '\\' on your PC console to start a new 2-second window **********\r\n");
    }

    return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 51,368,960 ops (50,432,000 macc; 936,960 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 7,340,032 ops (7,077,888 macc; 262,144 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 19,267,584 ops (18,874,368 macc; 393,216 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 19,070,976 ops (18,874,368 macc; 196,608 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 4,792,320 ops (4,718,592 macc; 73,728 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4: 600,064 ops (589,824 macc; 10,240 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5: 295,936 ops (294,912 macc; 1,024 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6: 2,048 ops (2,048 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 57,776 bytes out of 442,368 bytes total (13.1%)
  Bias memory:   2 bytes out of 2,048 bytes total (0.1%)
*/
